# This workflow will install dev dependencies, and generate documentation.

name: pdberellig documentation

on:
  push:
    branches:
      - main

jobs:
  documentation:
    name: Generate documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Define a cache for the virtual environment based on the dependencies lock file
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the package without dependencies
        run: poetry install --only-root
      - name: Install documentation dependencies only
        run: poetry install --only doc
      - run: |
          cd doc
          poetry run sphinx-build -b html . _build/html
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/_build/html
